## 5. <strong>NumPy 배열</strong>

In [1]:
# Python 패키지 설치 명령어
!pip install numpy

In [2]:
# NumPy 불러오기
import numpy as np

### <strong> 5.1 NumPy 배열 생성

In [3]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1, 2, 3, 4, 5, 6]
my_arr = np.array(my_lst)

my_arr

array([1, 2, 3, 4, 5, 6])

In [4]:
# [+] 리스트/NumPy 배열 동시에 생성
my_array = np.array([1, 2, 3, 4, 5, 6])
my_array

array([1, 2, 3, 4, 5, 6])

#### 리스트 컴프리헨션 vs NumPy 배열

In [5]:
prices = [20, 40, 35, 10, 25, 56]

# [+] 리스트 컴프리헨션을 이용하여 5달러씩 가격을 일괄적으로 할인하기
new_prices = [price-5 for price in prices]

new_prices

[15, 35, 30, 5, 20, 51]

In [6]:
# [+] NumPy 배열의 연산을 통한 5달러씩 가격을 일괄적으로 할인하기
prices_arr = np.array(prices)   # 배열 생성
prices_arr -= 5   # 가격 수정

prices_arr

array([15, 35, 30,  5, 20, 51])

#### 예제: 시험 점수 처리

In [7]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

total_test = np.array([test_1, test_2, test_3])

In [8]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = [price+2 for price in test_3]

test_3_fixed

[89, 87, 74, 92, 94]

In [9]:
# [+] 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = test_1 + test_2 + test_3

total_grade

array([258, 279, 246, 274, 270])

In [10]:
# [+] 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = (test_1 + test_2 + test_3)/3

final_grade

array([86.        , 93.        , 82.        , 91.33333333, 90.        ])

In [11]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]

jeremy_test_2

93

In [12]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]

manual_adwoa_test_1

array([94, 88])

In [13]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1, test_2, test_3])

student_scores

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91],
       [ 87,  85,  72,  90,  92]])

In [14]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
student_scores[2][0]

87

In [15]:
# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
student_scores[:,-1]

array([87, 91, 92])

#### 배열 원소 단위의 논리 연산

In [16]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])

# [+] 150 이상 여부를 마스킹
mask = a >= 150

mask

array([False, False, False, False, False, False, False, False])

In [17]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a>30]

selected

array([88])

In [18]:
# [+] 논리식 결합: 논리합
selected = a[(a > 5) | (a < 3)]

selected

array([ 1, 20,  6, 28, 88,  7, 12])

In [19]:
# [+] 논리식 결합: 논리곱
selected = a[(a > 7) & (a > 30)]

selected

array([88])

In [20]:
# [+] 정수 배열 생성
np.arange(11, 33, 3)

array([11, 14, 17, 20, 23, 26, 29, 32])

In [21]:
# [+] 난수 배열 생성
np.random.seed(5)
arr=np.random.randint(10,size=(3,5))

arr

array([[3, 6, 6, 0, 9],
       [8, 4, 7, 0, 0],
       [7, 1, 5, 7, 0]])

### <strong>5.2 배열 조작 연산</strong>

In [22]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상
print(arr.size)     # 크기
print(arr.dtype)    # 데이터 타입
print(arr.itemsize) # 원소별 메모리 크기(bytes)
print(arr.nbytes)   # 전체 메모리 크기

2
(3, 5)
15
int32
4
60


In [23]:
# [+] 배열 슬라이싱
arr = np.arange(10)
print(arr)

print(arr[2:7])  # 슬라이싱(start:stop)
print(arr[:5])   # 시작 인덱스 생략(:stop)
print(arr[5:])   # 종료 인덱스 생략(start:)
print(arr[::2])  # 간격(::interval)
print(arr[1:8:2])  # 슬라이싱(start:stop:interval)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7]


In [36]:
# [+] 난수 배열 생성
np.random.seed(5)  # [+] 시드 설정
arr = np.random.randint(10, size=(6, 8))  # [+] 난수 배열 생성

arr

array([[3, 6, 6, 0, 9, 8, 4, 7],
       [0, 0, 7, 1, 5, 7, 0, 1],
       [4, 6, 2, 9, 9, 9, 9, 1],
       [2, 7, 0, 5, 0, 0, 4, 4],
       [9, 3, 2, 4, 6, 9, 3, 3],
       [2, 1, 5, 7, 4, 3, 1, 7]])

In [38]:
# [+] 다차원 배열 슬라이싱
arr[1:4, 4:]

array([[5, 7, 0, 1],
       [9, 9, 9, 1],
       [0, 0, 4, 4]])

In [26]:
# 배열 슬라이스 = 뷰(view)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[3 6]
 [8 4]]
[[99  6]
 [ 8  4]]
[[99  6  6  0  9]
 [ 8  4  7  0  0]
 [ 7  1  5  7  0]]


In [27]:
# 배열 복사본 생성
arr_sub = arr[:2, :2].copy()

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[99  6]
 [ 8  4]]
[[99  6  6  0  9]
 [ 8  4  7  0  0]
 [ 7  1  5  7  0]]


In [28]:
# [+] 배열 재구조화: reshape()
x = np.arange(10) # 0~9로 이루어진 배열 생성 (10,)
print(x)
print(x.shape)

x = x.reshape(2, 5)  # 배열을 2X5 형상으로 재구조화
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [29]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr_new = x[:, np.newaxis]
print(arr_new)
print(arr_new.shape)

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
(2, 1, 5)


#### <strong> 배열 연결하기</strong>

In [30]:
# 세 개의 배열 생성
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [31]:
# [+] 배열 연결: np.concatenate()
arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]


In [32]:
# [+] 배열 연결: 종연결
arr_total = np.vstack([arr_1, arr_2, arr_3])

arr_total

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# [+] 배열 연결: 횡연결
arr_total = np.hstack([arr_1, arr_2, arr_3])

arr_total

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

# [+] 배열 분할 [1,2,3], [99,99], [3,2,1]
arr_1, arr_2, arr_3 = np.split(arr, [3, 5])  
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
